### ISSUE TITLE
gitlab-api-v4: problem with whitespace in parameter parsing

### ISSUE THREAD

**Issue by gregoa** [bluefeet/GitLab-API-v4#10]
When I run

```
gitlab-api-v4 create_project --name="pperl" --namespace_id="2667" --visibility="public" --import_url="https://anonscm.debian.org/git/pkg-perl/attic/pperl.git" --description='Debian package pperl'
```
I get the error:
```
create_project must be called with 0 to 1 arguments at /usr/bin/gitlab-api-v4 line 86.
```

The problem is the parsing of parameter values in ```gitlab-api-v4``` line 58: ```(=(\S+)|)```. So a value with whitespace, in my example the ```--description="Debian package pperl"```, doesn't match, the ```elsif``` fails, we don't have a ```$params->{description}``` but the whole string is pushed unto ```@args```, and ```create_repo``` errors out.

With some Data::Dumper()ing:
```
$VAR1 = 'ARGV';
$VAR2 = 'create_project';
$VAR3 = '--name=pperl';
$VAR4 = '--namespace_id=2667';
$VAR5 = '--visibility=public';
$VAR6 = '--import_url=https://anonscm.debian.org/git/pkg-perl/attic/pperl.git';
$VAR7 = '--description=Debian package pperl';
$VAR8 = 'args';
$VAR9 = '--description=Debian package pperl';
$VAR10 = 'params';
$VAR11 = {
           'name' => 'pperl',
           'visibility' => 'public',
           'import_url' => 'https://anonscm.debian.org/git/pkg-perl/attic/pperl.git',
           'namespace_id' => '2667'
         };
```

(Unsurprisingly, a ```--description``` value without whitespace works.)

**Comment by bluefeet** [comment]
Thanks for the bug report!  This patch should fix it up.

**Comment by gregoa** [comment]
On Fri, 02 Mar 2018 20:39:54 +0000, Aran Deltac wrote:

> Thanks for the bug report!  This patch should fix it up.

Great, thank you! 


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-   NP: Ry Cooder: Crazy 'Bout An Automobile (Every Woman I Know)

**Comment by bluefeet** [comment]
v0.05 is released and will be hitting your local cpan mirror sometime in the next few hours.

**Comment by gregoa** [comment]
On Tue, 06 Mar 2018 10:26:33 -0800, Aran Deltac wrote:

> v0.05 is released and will be hitting your local cpan mirror sometime in the next few hours.

Thank you!
Uploaded to Debian.

Cheers,
gregor 

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-   NP: The Chieftains: The Foggy Dew (With Sinéad O'connor)
