### ISSUE TITLE
(un)block_user(<id>) succeeds, but reports errors on deserialization of response

### ISSUE THREAD

**Issue by jansmets** [bluefeet/GitLab-API-v4#15]
Data was $VAR1 = [
          'true'
        ];
  at /home/builder/jan/gitutils/gitlab/perllib/lib/perl5/Role/REST/Client/Serializer.pm line 80, <UF> line 1698.
Couldn't deserialize data with application/json: JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at /home/builder/jan/gitutils/gitlab/perllib/lib/perl5/Data/Serializer/JSON.pm line 17, <UF> line 1698.

**Comment by bluefeet** [comment]
Duplicate of #12.
I expect to have the fix released today.
