### ISSUE TITLE
all api calls are paginated

### ISSUE THREAD

**Issue by jansmets** [bluefeet/GitLab-API-v4#16]
It seems that (almost?) all API calls are paginated. I unfortunately had to find this out the hard way.
eg, <host>/api/v4/users/<user_id>/keys?page=1&per_page=1

The python client seems to fully implement this: 
http://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination

Would it be possible to implement something like: 
```
    #my $current_gitlab_keys = $api->user_ssh_keys($account->{id});
    my $current_gitlab_keys = $api->paginator('user_ssh_keys', $account->{id}, { per_page => 100} )->all();

sub user_ssh_keys {
    my $self = shift;
    croak 'user_ssh_keys must be called with 1 to 2 arguments' if @_ < 1 or @_ > 2;
    croak 'The last argument (\%params) to user_ssh_keys must be a hash ref' if defined($_[1]) and ref($_[1]) ne 'HASH';
    my $params = (@_ == 2) ? pop() : undef;
    my $options = {};
    $options->{query} = $params if defined $params;
    return $self->_call_rest_method( 'GET', 'users/:user_id/keys', [@_], $options );
}
```
Or perhaps make pagination transparent.

Thanks!

**Comment by bluefeet** [comment]
After some head scratching trying to figure out what it is you are actually saying I think I figured it out.  Please confirm:

The user_ssh_keys method does not support a parameters hashref so when you use it with paginator() it fails.  Also, you suspect many other API endpoints which returns lists to have this same issue.

Is that right?

**Comment by jansmets** [comment]
Yes, entirely correct. My apologies for the limited explanation.

**Comment by bluefeet** [comment]
Awesome.  Fix incoming!

**Comment by bluefeet** [comment]
I manually went through all of GitLab's ruby code for the api and found the endpoints with support pagination parameters.  So this fix should do the job.

v0.08 will be hitting your local CPAN mirror within a couple hours.

**Comment by jansmets** [comment]
Thanks!
