### ISSUE TITLE
Problem with delete_project_hook

### ISSUE THREAD

**Issue by gregoa** [bluefeet/GitLab-API-v4#17]
`delete_project_hook` partially fails with

```
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/perl5/GitLab/API/v4/RESTClient.pm line 142.
```

This seems to happen when a hook to be deleted exists; in this case `$res->{content}` in /usr/share/perl5/GitLab/API/v4/RESTClient.pm is `undef`. (Which kind of contradicts the documentation at https://docs.gitlab.com/ce/api/projects.html#delete-project-hook which claims "If the project hook is available before it is returned in the JSON response or an empty response is returned.")

I've now set decoding to false, which makes the problem go away. Not sure if this is the best solution ...

```diff
diff --git a/lib/GitLab/API/v4.pm b/lib/GitLab/API/v4.pm
index 558aaea..d4df447 100644
--- a/lib/GitLab/API/v4.pm
+++ b/lib/GitLab/API/v4.pm
@@ -6053,6 +6053,7 @@ sub delete_project_hook {
     croak 'The #1 argument ($project_id) to delete_project_hook must be a scalar' if ref($_[0]) or (!defined $_[0]);
     croak 'The #2 argument ($hook_id) to delete_project_hook must be a scalar' if ref($_[1]) or (!defined $_[1]);
     my $options = {};
+    $options->{decode} = 0;
     return $self->_call_rest_client( 'DELETE', 'projects/:project_id/hooks/:hook_id', [@_], $options );
 }
```

This is on salsa.debian.org which runs Gitlab
Version:  10.8.1
Revision: 3d6659ddd84

Also interesting: When I try to delete a non-existing hook id, I get:
```
Error DELETEing https://salsa.debian.org/api/v4/projects/perl-team%2Fmodules%2Fpackages%2Fpkg-perl-tools/hooks/28929 (HTTP 404): Not Found {"message":"404 Not found"} at /home/gregoa/src/git-pkg-perl/meta/packages/pkg-perl-tools/scripts/salsa line 326.
```

which kind of makes sense, except that it contradicts the documentation as well ("This is an idempotent method and can be called multiple times. Either the hook is available or not.").

Cheers,
gregor, Debian Perl Group

**Comment by bluefeet** [comment]
Thanks for the bug report!  I ended up writing some live tests and verified the correct behavior of the 4 project hook methods.  See the Changes file for details.

**Comment by gregoa** [comment]
On Tue, 05 Jun 2018 23:37:34 -0700, Aran Deltac wrote:

> Thanks for the bug report! I ended up writing some live tests and
> verified the correct behavior of the 4 project hook methods. See
> the Changes file for details.

Great news, thank you!

0.10 uploaded to Debian.

Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-   NP: R.E.M.: Bad Day
