### ISSUE TITLE
projects() shoud accept project_path

### ISSUE THREAD

**Issue by guimard** [bluefeet/GitLab-API-v4#22]
Hello,

Thanks for writing this API. I had to write this to get a project by path:
```perl
sub GitLab::API::v4::project_by_path {                                              
    my $self = shift;                                                               
    return $self->_call_rest_client('GET', 'projects/%s', [shift], {});             
}
```
Coud you modify `projects()` method ?

Cheers,
Xavier

**Comment by bluefeet** [comment]
Again, I think you mean `project()`, not `projects()` (you are retrieving a single project, not many).

`project()` already accepts a `$project_id`.

Per https://metacpan.org/pod/GitLab::API::v4#Project-ID anywhere where a $project_id is accepted you /should/ be able to pass a path instead.  Have you tried something like `my $project = $api->project( $path );` ?
