### ISSUE TITLE
group() should accept parameters

### ISSUE THREAD

**Issue by guimard** [bluefeet/GitLab-API-v4#23]
Hello,

to access to a group with a lot of projects, I had to write this since `groups()` doesn't accept a second parameter:
```
sub GitLab::API::v4::group_without_projects {                                       
    my $self = shift;                                                               
    return $self->_call_rest_client('GET', 'groups/:group_id', [@_],                
        { query => { with_custom_attributes => 0, with_projects => 0 } });          
}
```
Could you update it ?

Cheers,
Xavier

**Comment by bluefeet** [comment]
Looks to me like your request is for `group()`, not `groups()`.  Fixing!

**Comment by guimard** [comment]
Hello,

no this is not the same. I can't call `group()` with 2 arguments so it is impossible to query for a group without `with_project` and for group with a lot of projects it takes a long time.

Anyway since you close this issue, I'll keep my hook.

Cheers,
Xavier

**Comment by bluefeet** [comment]
Dude, I didn't just close the issue, I provided a fix.  Could you please comment on fix which enabled parameters in the `group()` method?  I believe this fixes your issue.  Once you confirm, I'll release on CPAN.

**Comment by guimard** [comment]
Sorry, seems OK now. Thanks !

**Comment by bluefeet** [comment]
Allright, version 0.13 including this fix is released and will hit your local CPAN mirror within a couple hours.

Thanks for the bug report!

**Comment by guimard** [comment]
Pushed to Debian/unstable just now. Thanks
