### ISSUE TITLE
cli tool greedily eats method params

### ISSUE THREAD

**Issue by tyldum** [bluefeet/GitLab-API-v4#24]
Trying to manipulate the JIRA service which has an URL param, the cli tool will eat it and replace the gitlab url with the jira url.
`gitlab-api-v4 edit_project_service project jira --url=https://jira.example.com/`

**Comment by tyldum** [comment]
Sadly, that does not work:
`edit_project_service must be called with 2 to 3 arguments at ...bin/gitlab-api-v4 line 89.`

**Comment by bluefeet** [comment]
I think that 56c8a3d15a84d20ddf108397c0f716abff955455 solves the issue correctly (making -- work as expected).  I also added some extra debug output, so if you pass --verbose you get to see the final values for the method, args, and params.

**Comment by tyldum** [comment]
Yes, it works.
For a general purpose tool that could get abused in unforeseeable ways I would say this would be great, while for a specialized tool like this I feel it should be combined with `require_order` to GetOpt to simply work better out of the box without stumbling into an issue and then realize you must use '--' before arguments.
There is also a risk that stuff that used to work without '--' at some point stops working because more arguments are added to `gitlab-api-v4` that happen to overlap with something in the GitLab API.

**Comment by bluefeet** [comment]
I'm still not satisfied with this solution.  It could break existing arguments that people rely on, yet at the same time does not fully resolve all the cases where someone could accidentally screw up.

Instead I've modified parameters to not use option formatting altogether.  This also breaks any existing setups people have even more than using `require_order`, but I think it's a good change and removes all the ambiguity.  Here's what it'll look like:

    gitlab-api-v4 --url=xxx some-method url:yyy

Here's the commit that makes this work: 95a84981d3f12c3eb6341a4e61c4db1c3fb34f7c

**Comment by bluefeet** [comment]
v0.15 was released yesterday with this change.

@gregoa I wanted you to be aware that this change breaks `gitlab-api-v4` backwards compatibility:

```
BREAKING CHANGE: gitlab-api-v4 now takes parameters in the form of param:value
rather than --param=value.  This is to avoid foot-gun ambiguities when options
have the same names as parameters (such as --url).
```

I'm not sure if over there in the Debian world if you are using the `gitlab-api-v4` script, but if you are, heads up when you upgrade!

@tyldum thanks for the prodding.

**Comment by gregoa** [comment]
On Thu, 10 Jan 2019 06:51:32 -0800, Aran Deltac wrote:

> @gregoa I wanted you to be aware that this change breaks `gitlab-api-v4` backwards compatibility:

Thanks for the heads-up, much appreciated.

I'm not aware of any tools using the script (and not the module
itself), so I went ahead with the upload, but included your warning
for users.
