### ISSUE TITLE
user() should accept no parameters

### ISSUE THREAD

**Issue by felsgaertner** [bluefeet/GitLab-API-v4#32]
If you call /user without any parameter, you get the details of the user which the token belongs to:

```shell
curl --header "PRIVATE-TOKEN: <token>" "https://gitlab.com/api/v4/user"
```

This should be able with GitLab-API-v4, which is not possible yet. The current version v4-0.17 complains about missing parameters.

**Comment by bluefeet** [comment]
This is already implemented as the `current_user()` method, documented at:

https://metacpan.org/pod/GitLab::API::v4#Users

**Comment by felsgaertner** [comment]
Ok, thanks. Maybe I was stuck to tight to the upstream API docs. Didn't find that.
