### ISSUE TITLE
add method for commit references

### ISSUE THREAD

**Issue by felsgaertner** [bluefeet/GitLab-API-v4#33]
The [API](https://docs.gitlab.com/ce/api/commits.html#get-references-a-commit-is-pushed-to) provides (since 10.6) a way to filter the type of references for a commit. 

v4-0.17 complains if this filter is added to the method call commit(). I would be nice to have this in the module.

**Comment by bluefeet** [comment]
The `commit()` method is generated for this endpoint:

    - commit: commit = GET projects/:project_id/repository/commits/:commit_sha

Which is documented here:

https://docs.gitlab.com/ce/api/commits.html#get-a-single-commit

The endpoint you linked to is an entirely new enpoint that this client does not yet support.  I'll update the ticket title to reflect this.
