### ISSUE TITLE
Add support for releases api

### ISSUE THREAD

**Issue by felsgaertner** [bluefeet/GitLab-API-v4#34]
Since version 11.7 GitLab has a new API for releases and release notes, the old fashioned way via tags has been deprecated:

https://docs.gitlab.com/ee/api/releases/

>>>
Releases API
Version history

    Introduced in GitLab 11.7.
    Using this API you can manipulate GitLab’s Release entries.
    For manipulating links as a release asset, see Release Links API.
>>>

There is no support in this CPAN module yet. Do you plan to integrate this API?

**Comment by bluefeet** [comment]
This ticket is the plan!

Thanks for reporting, I'll get this added shortly.

**Comment by bluefeet** [comment]
When you say "old fashioned way via tags" are you referring to these two endpoints?
https://docs.gitlab.com/ce/api/tags.html#create-a-new-release
https://docs.gitlab.com/ce/api/tags.html#update-a-release

Where is the notice that these two endpoints have been deprecated?

I looked here and nothing mentions a deprecation:
https://about.gitlab.com/2019/01/22/gitlab-11-7-released/

I also dug through the detailed release notes and could not find anything:
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md

I mean, it makes sense that those two endpoints would be deprecated with the release of the new releases API in 11.7, but I see nothing stating that.  It doesn't change how I will handle this ticket, I just want to make sure I have my facts straight.

Please advise.  Thanks.

**Comment by bluefeet** [comment]
373c1937753038afdafe534b777933212175d583 should do the job.

**Comment by felsgaertner** [comment]
Regarding the "deprecated" statement, I only have this source code reference:
https://github.com/xanzy/go-gitlab/blob/master/tags.go#L124

Perhaps Xanzy knows more...

**Comment by bluefeet** [comment]
Thanks for that!

**Comment by bluefeet** [comment]
This has been released.  Version `0.20` should hit your local CPAN mirror within an hour or two.

**Comment by felsgaertner** [comment]
Thanks for the publish.
