### ISSUE TITLE
Use carp, not croak.

### ISSUE THREAD

**Issue by felsgaertner** [bluefeet/GitLab-API-v4#35]
Hi Aran, 

I really like this module, but things would be a lot easier if it would continue after 4xx status codes.

For example, I want to maintain release notes for tags using code like this:

~~~perl
if ( $api->release( ... ) ) {
  $api->update_release( ... )
}
else {
  $api->create_release( ... ) 
}
~~~

Otherwise I would hae to paginate through all existing tags, searching for eventually existing release notes.

Unfortunately the module exits in the if statement since the release does not exist yet.

I would suggest to replace the croak() calls with carp() returning undef, and perhaps a "quiet" mode to suppress the error messaages.

Thanks, Volker

**Comment by bluefeet** [comment]
Taking a look, in your example `$api->release` should be returning `undef` per the documentation.

> The API methods will all throw a useful exception if an unsuccessful response is received from the API. That is except for GET requests that return a 404 response - these will return undef for methods that return a value.

**Comment by bluefeet** [comment]
You're going to have to provide a better example.  If I provide a non-existing project ID and/or non-existing release ID I get `undef` back.

Please also include a more real-world test case (no `...`s) and the error message you are receiving.

**Comment by felsgaertner** [comment]
Ok, but currently I am working with a self-hosted instance of GitLab CE, so I need to write some example code for GitLab.com.

**Comment by felsgaertner** [comment]
An example without code:

from Perl docs at [Carp SYNOPSIS](https://perldoc.perl.org/Carp.html):
~~~perl
    use Carp;

    # warn user (from perspective of caller)
    carp "string trimmed to 80 chars";

    # die of errors (from perspective of caller)
    croak "We're outta here!";
~~~
So "croak" dies after the error has been printed, it does not return.

Now lookinng at the [RESTClient}(https://github.com/bluefeet/GitLab-API-v4/blob/e5863eab5248aef805aeab1b06721c1b97d7fc57/lib/GitLab/API/v4/RESTClient.pm):

* L167: returns undef for a GET request with status error 404.
* L191: any other request with status other then "success" runs into the croak sprintf() block.

API examples:
* create tag = POST request
* update release note = PUT request

Possible error codes:
* 403 forbidden
* 407 method not allowed (e.g. access token with just API access, repo r/w access missing)

All those cause the current implementation to print the error message and die.

**Comment by felsgaertner** [comment]
Example code and [project](https://gitlab.com/felsgaertner/apitest):

* apitest-ifelse.pl -> fails with error 403, but should work.
* apitest-trycatch.pl -> works.

**Comment by bluefeet** [comment]
I don't think 403 or 407 responses should return `undef`, those are errors worthy of an exception.

code | response
---- | --------
`$api->response($unknown_project_id, $unknown_tag_name)` | `404`
`$api->response($unknown_project_id, $known_tag_name)` | `404`
`$api->response($known_project_id, $unknown_tag_name)` | `403`
`$api->response($known_project_id, $known_tag_name)` | `200`

I think the question we should be asking is:
Why does a request for an unknown release tag return a 403 rather than a 404?  That seems broken and inconsistent with the rest of the API.  Perhaps open a ticket with GitLab and get them to fix it?

**Comment by felsgaertner** [comment]
You could try, but I think that will take quite long. A workaround in your module could be way faster.

IMHO the problem is that the module RESTclient dies immediately if such errors occur, making any error handling in the main package worthless. That's why I am asking for carp instead of croak.
