### ISSUE TITLE
Bad fork_project URL

### ISSUE THREAD

**Issue by jwilk** [bluefeet/GitLab-API-v4#4]
author/sections/projects.yml reads:
```
- fork_project: POST /pojects/fork/:project_id?
```

I haven't tested it, but I don't think this is the correct URL.
"p**r**ojects" is misspelled, and the [documentation](https://docs.gitlab.com/ce/api/projects.html#fork-project) says the project id should be in front of `/fork`.

**Comment by bluefeet** [comment]
Thank you!  The next release will include a fix for this.
