### ISSUE TITLE
Add API for project remote_mirrors 

### ISSUE THREAD

**Issue by baby-gnu** [bluefeet/GitLab-API-v4#46]
Hello.

Since version 12.9, GitLab support `remote_mirrors` configuration: https://docs.gitlab.com/ce/api/remote_mirrors.html

Is it possible to include it?

Regards.

**Comment by bluefeet** [comment]
Thanks for the request and I apologize for the delay.

This will be released onto CPAN later today.

**Comment by baby-gnu** [comment]
Don't apologize, the timing is fine for me.

Thanks a lot.
