### ISSUE TITLE
Fix upload_file_to_project method to actually upload files

### ISSUE THREAD

**Issue by rugydp** [bluefeet/GitLab-API-v4#6]
Wondeful API but I struggle with `upload_file_to_project` in code and on cli (but works with 'curl')

```
my $filepath = $attachement_part->parts(1)->bodyhandle->path;   
    #print Dumper $filepath;  
    my $upload = $api->upload_file_to_project(  
        $project_id,  
        {file => $filepath}
    );
```
   
Not matter what I try, it fails with_
```
Bad Request {error => 'file is invalid'}
```

Can you please provide a short working code example?

Thank you!

**Comment by bluefeet** [comment]
Hello.  Could you paste the working Curl command so that I can compare that to what this module is doing?  Thanks!

**Comment by rugydp** [comment]
Request: 
```
Hi 

curl --request POST --header "PRIVATE-TOKEN: xxxxxxxxxxxxxxxxxx" --form "file=@/tmp/file.png" https://some.gitlabserver.com/api/v4/projects/57/uploads
```

Response:

```
{"alt":"file","url":"/uploads/a1ea25692df274f343928cf0bb9b4119/file.png","markdown":"![file](/uploads/a1ea25692df274f343928cf0bb9b4119/file.png)"}
```

Thanks!

**Comment by bluefeet** [comment]
OK, so the current client does not support file uploads.  A complete oversight.  Likely not too difficult to add.  I'm pretty sure this only affects the `upload_file_to_project` method.

**Comment by bluefeet** [comment]
A solution for this is getting closer with 2fa589d5d4b98c8eba3161883e222c606e271b66.

**Comment by bluefeet** [comment]
I removed upload_file_to_project for now in 6afa05e7409dbf448f277b90be66510d4d8fb26c.

**Comment by bluefeet** [comment]
Fixed!
