### ISSUE TITLE
Encoding issue ("Wide character in print ...")

### ISSUE THREAD

**Issue by gregoa** [bluefeet/GitLab-API-v4#7]
It looks like there's some encoding issue with non-ascii characters returned by the GitLab API.

Example:
```
% gitlab-api-v4 --url=https://salsa.debian.org/api/v4/ tags debian/debhelper  
Wide character in print at /usr/bin/gitlab-api-v4 line 94.

%
```
The server's response can be seen at https://salsa.debian.org/api/v4/projects/debian%2Fdebhelper/repository/tags

Cheers,
gregor

**Comment by bluefeet** [comment]
This appears to have been already reported in #5 and fixed in the 0.03 release.  Could you confirm which version of GitLab::API::v4 you are using?

**Comment by gregoa** [comment]
On Fri, 02 Feb 2018 11:34:16 -0800, Aran Deltac wrote:

> This appears to have been already reported in #5 and fixed in the
> 0.03 release. Could you confirm which version of GitLab::API::v4
> you are using?

Sorry for not mentioning the version, but I'm indeed already using
0.03.

Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-

**Comment by gregoa** [comment]
Ah, I missed your later edit & fix. Thank you!
