### ISSUE TITLE
Warnings from Role::REST::Client

### ISSUE THREAD

**Issue by gregoa** [bluefeet/GitLab-API-v4#9]
I'm seeing warnings like this:

```
Use of uninitialized value in pattern match (m//) at /usr/share/perl5/Role/REST/Client.pm line 170.
```

As far as I can see, they appear on each invocation of `delete_project_hook()` and of `delete_project_service()`.

From Role::REST::Client (version 0.22; line numbers added):

```
169    my $use_serializer = exists $args->{deserializer}
170        ? defined $args->{deserializer} ? 1 : 0
171        : $res->header('Content-Type') !~ m{(?:text/(?:plain|html)|application/octet-stream)};
```

Looks like $res->header('Content-Type') doesn't exist. And if I Data::Dumper $res->headers in Role::REST::Client after line 171, then I indeed don't see any Content-Type in the response to `delete_project_hook()`.

Cheers,
gregor

**Comment by bluefeet** [comment]
Hey @jjatria do you have any thoughts about this one?  I haven't dug in yet, but figure I'd call you out here in case you had the tuits to take a look.

**Comment by jjatria** [comment]
This seems to me to be another issue that is better solved upstream. GitLab::API::v4 does not seem to be doing anything wrong.

I've sent in [a PR to fix this](https://github.com/kaare/Role-REST-Client/pull/38). Let's see what happens.

**Comment by jjatria** [comment]
The pull request was merged 🎉 
This issue _should_ be fixed. 👍

**Comment by gregoa** [comment]
I've applied the patch for R::R::C locally, and I can confirm that the warnings are gone. Thanks @jjatria and @kaare!
Closing this issue.
